### ISSUE TITLE
hyperparameter chosen

### ISSUE THREAD

**Issue by lizijian-buaa** [AndPotap/afr#1]
Hi, can u provide the hyperparameter chosen for AFR for every dataset? Thx for your great work  BTW.

**Comment by shikaiqiu** [comment]
Hi there,

We did not record the optimal hyperparameters as it would depend on the seed etc. We provide the hyperparameter grid we searched over in Appendix B of our paper. You can also run the [notebooks](https://github.com/AndPotap/afr/tree/main/notebooks) which will search over that grid to reproduce our results.
